name: Playwright Tests

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

      USER_EMAIL: ${{secrets.USER_EMAIL}}
      USER_PASSWORD: ${{secrets.USER_PASSWORD}}
      USER_PHONE: ${{secrets.USER_PHONE}}

      TESTUSER_EMAIL: ${{secrets.TESTUSER_EMAIL}}
      TESTUSER_PASSWORD: ${{secrets.TESTUSER_PASSWORD}}
      TESTUSER_PHONE: ${{secrets.TESTUSER_PHONE}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npx playwright test

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          publish_branch: test-results
